### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by spidychoipro** [cquick00/scramble-generator#3]
downloaded file and check at the virus total and got this result

https://www.virustotal.com/gui/file/5733d43e6fbbf19f5728c7ff2b103ae69a8814447ca6ffed55a2f5b000d55d97?nocache=1

**Comment by cquick00** [comment]
Unfortunately it will happen from time to time that an AV will pick something up as a false positive. I have never heard of Bkav Pro, but seeing as they're the only scanner on VirusTotal that picked up my exe as having an issue, I'd wager that it's something wrong with their heuristics.

I should also note that I don't have a signing certificate, nor am I willing to pay for one when my code is freely available and can be built from source if needed. I just make the exe available as an easy to use solution if people want it. it could be entirely possible that their issue is related to that. Usually companies like Microsoft would also pick that up though so I doubt it.
